name: Update Kernel

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        repository: coolsnowwolf/lede

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt update
        sudo -E apt -y full-upgrade
        sudo -E apt -y install aria2 build-essential flex gawk gettext git libncurses6 libssl-dev python3-distutils rsync unzip zlib1g-dev file wget quilt
        sudo -E apt -y autoremove --purge
        sudo -E apt clean

    - name: Update Kernel
      run: |
        wget https://github.com/lovehackintosh/Actions-OpenWrt/raw/update-kernel/OpenWRT_Refresh_Patches.bash
        chmod 777 ./OpenWRT_Refresh_Patches.bash
        ./OpenWRT_Refresh_Patches.bash -u 6.1
        ./OpenWRT_Refresh_Patches.bash -u 5.15
        ./OpenWRT_Refresh_Patches.bash -u 5.10
        ./OpenWRT_Refresh_Patches.bash -u 5.4
        git restore target/linux/rockchip/patches-5.15/013-v5.16-arm64-dts-rockchip-move-rk3568-dtsi-to-rk356x-dtsi.patch
        git diff > 1.patch

    - name: Upload Patches
      uses: actions/upload-artifact@main
      with:
        name: 1.patch
        path: 1.patch

